general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =

    path = screenshot

    blur_passes = 3
    blur_size = 8

    noise = 0.0117
    contrast = 1.2
    brightness = 0.08
    vibrancy = 0.18
    vibrancy_darkness = 0.0
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date +"%H:%M")"

    color = rgba(191,207,224,1.0)

    font_size = 72
    font_family = Sans

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date +"%A, %d %B")"

    color = rgba(191,207,224,0.75)

    font_size = 20
    font_family = Sans

    position = 0, 65
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 320, 56
    outline_thickness = 2

    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true

    outer_color = rgba(69,69,90,1.0)
    inner_color = rgba(9,10,17,0.85)

    font_color = rgba(191,207,224,1.0)

    fade_on_empty = false

    rounding = 14

    check_color = rgba(191,207,224,1.0)
    fail_color = rgba(255,80,80,1.0)

    placeholder_text = Password...

    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =

    text = Press Enter to unlock

    color = rgba(191,207,224,0.45)

    font_size = 14
    font_family = Sans

    position = 0, -110
    halign = center
    valign = center
# }
