hl.on("hyprland.start", function()
hl.exec_cmd("pkill waybar; waybar -c /home/koen/.config/waybar/configtop -s /home/koen/.config/waybar/style.css &")
hl.exec_cmd("pkill waybar; waybar -c /home/koen/.config/waybar/configbottom -s /home/koen/.config/waybar/style.css &")
hl.exec_cmd("systemctl --user start hyprpolkitagent")
hl.exec_cmd("hyprpaper")
hl.exec_cmd("sh -c 'sleep 2 && firefox'", { workspace = "6 silent" })
hl.exec_cmd("steam")
hl.exec_cmd("dunst")
hl.exec_cmd("discord")
hl.exec_cmd("hypridle")
hl.exec_cmd("wl-clipboard")
hl.exec_cmd("tumblerd")
hl.exec_cmd("cliphist wipe")
hl.exec_cmd("wl-paste --type text --watch cliphist store")
hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
